export const GET_ERRORS = 'GET_ERRORS'
export const USER_LOADING = 'USER_LOADING'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'

export const GET_ANIMALS = 'GET_ANIMALS'
export const ADD_ANIMAL = 'ADD_ANIMAL'
export const UPDATE_ANIMAL = 'UPDATE_ANIMAL'
export const DELETE_ANIMAL = 'DELETE_ANIMAL'
